# Specify the Docker image to use for the jobs
image: docker:stable

# Define stages for the pipeline
stages:
  - build_frontend
  - build_backend
  - test_frontend
  - test_backend
  # - deploy_frontend
  # - deploy_backend

# Frontend build stage
build_frontend:
  stage: build_frontend
  before_script:
    - cd CSC3032-2324-TEAM15/Insurance-In-Review
  script:
    - npm install
    - npm run build

# Backend build stage
build_backend:
  stage: build_backend
  before_script:
    - cd CSC3032-2324-TEAM15/API/cmd 
  script:
    - go build

# Test stage
test_frontend:
  stage: test_frontend
  before_script:
    - cd CSC3032-2324-TEAM15/Insurance-in-Review
  script:
    - echo "Running tests..."
    - npm install
    - npm test ./...

# Test stage
test_backend:
  stage: test_backend
  before_script:
    - cd CSC3032-2324-TEAM15/API/cmd
  script:
    - echo "Running tests..."
    - go test ./...

# # Deployment stage
# deploy_frontend:
#   stage: deploy_frontend
#  before_script:
#    - cd ./Insurance-in-Review
#   script:
#     - echo "Deploying the frontend application..."
#     - docker 
#   only:
#     - main # Only deploy when changes are pushed to the main branch

# # Deployment stage
# deploy_backend:
#   stage: deploy_backend
# before_script:
#   - cd ./API
#   script:
#     - echo "Deploying the backend application..."
#     - docker
#   only:
#     - main # Only deploy when changes are pushed to the main branch

