# Specify the Docker image to use for the jobs
image: docker:stable

# Define stages for the pipeline
stages:
  - build_frontend
  - build_backend
  - test
  - deploy

# Frontend build stage
build_frontend:
  stage: build_frontend
  before_script:
    - cd Insurance-in-Review # Assuming frontend code is in a directory named 'frontend'
  script:
    - npm install
    - npm run build

# Backend build stage
build_backend:
  stage: build_backend
  before_script:
    - cd API/cmd # Assuming backend code is in a directory named 'backend'
  script:
    - go build

# Test stage
test_frontend:
  stage: test
  before_script:
    - cd Insurance-in-Review
  script:
    - echo "Running tests..."
    - npm install
    - npm test ./...

# Test stage
test_backend:
  stage: test
  before_script:
    - cd API/cmd
  script:
    - echo "Running tests..."
    - go test ./...

# # Deployment stage
# deploy_frontend:
#   stage: deploy
#   script:
#     - echo "Deploying the frontend application..."
#     - docker 
#   only:
#     - main # Only deploy when changes are pushed to the main branch

# # Deployment stage
# deploy_backend:
#   stage: deploy
#   script:
#     - echo "Deploying the backend application..."
#     - docker
#   only:
#     - main # Only deploy when changes are pushed to the main branch

