version: "4.25" 
services:
   web:
       build: .
       ports:
           - "3000:3000"
       environment:
           MONGODB_URI: mongodb+srv://marcvillareal30:jxzecGkV3ugG5w3Y@insurance.c0iumta.mongodb.net/
        
